version: "3.8"
services:
    server:
      build: ./backend
      ports:
        - "8181:8181"
      volumes:
        - ./backend:/code
      environment:
        FLASK_ENV: development
    web:
      build: ./frontend
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/code

